#!/bin/zsh

# Define the directory where paths will be saved
SAVED_PATHS_FILE="$HOME/.saved_paths"

# Check if an argument is provided
if [[ $# -eq 0 ]]; then
    # If no argument is provided, save the path of the current directory
    current_path="$(pwd)"
    unique_variable="$(uuidgen)"  # Generating a unique variable name
    echo "export $unique_variable=\"$current_path\"" >> "$SAVED_PATHS_FILE"
    echo "Saved current directory path as variable $unique_variable"
    exit 0
fi

# Save the provided directory path to the file
echo "export $2=\"$1\"" >> "$SAVED_PATHS_FILE"
echo "Saved $1 as variable $2"

